name:                fp2023
version:             0.1.0.0
github:              "vipo/fp2023"
license:             BSD3
author:              "Viaceslav Pozdniakov"
maintainer:          "Viaceslav Pozdniakov"
copyright:           "2023 Viaceslav Pozdniakov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fp2023#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- ImportQualifiedPost

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - free
  - time
  - transformers
  - aeson
  - bytestring
  - yaml
  - lens

executables:
  fp2023-select-all:
    main:                Main.hs
    source-dirs:         app1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - extra
    - repline
    - terminal-size
  fp2023-select-more:
    main:                Main.hs
    source-dirs:         app2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - extra
    - repline
    - terminal-size
  fp2023-manipulate:
    main:                Main.hs
    source-dirs:         app3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - extra
    - repline
    - terminal-size
    - free
    - time
    - filepath
    - directory
    - bytestring
  fp2023-sql-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - pretty 
    - extra
    - repline
    - terminal-size
    - wreq
    - aeson
    - lens
    - yaml
    - bytestring
    - http-client
    - free
    - time
    - directory
    - filepath
  fp2023-sql-server:
    main:                Main.hs
    source-dirs:         server 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - extra
    - repline
    - terminal-size
    - Spock
    - http-types
    - text
    - mtl
    - aeson
    - time
    - free
    - filepath
    - directory
    - stm

tests:
  fp2023-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2023
    - hspec
    - free
    - time
